import { CartItem, Fruit } from "./types";

export const categories: string[] = [
  "Oranges",
  "Bananas",
  "Pineapple",
  "Apple",
  "Cherry",
];

export const fruitsData: Fruit[] = [
  {
    id: 1,
    name: "Australian Orange",
    category: "Oranges",
    price: "12.30",
    stars: 4,
    desc: "Sweet and juicy",
    shadow: "orange",
    image: require("../assets/images/orange.png"),
    color: (opacity: number) => `rgba(251, 216, 146, ${opacity})`,
  },
  {
    id: 2,
    name: "Spanish Orange",
    category: "Oranges",
    price: "8.00",
    stars: 4,
    desc: "Zesty flavor",
    shadow: "orange",
    image: require("../assets/images/orange2.png"),
    color: (opacity: number) => `rgba(251, 216, 146, ${opacity})`,
  },
  {
    id: 3,
    name: "Moroccan Orange",
    category: "Oranges",
    price: "8.50",
    stars: 5,
    desc: "Vibrantly sweet",
    shadow: "orange",
    image: require("../assets/images/orange3.png"),
    color: (opacity: number) => `rgba(251, 216, 146, ${opacity})`,
  },
  {
    id: 4,
    name: "Egyptian Orange",
    category: "Oranges",
    price: "15.30",
    stars: 2,
    desc: "Rich taste",
    shadow: "orange",
    image: require("../assets/images/orange4.png"),
    color: (opacity: number) => `rgba(252, 223, 116, ${opacity})`,
  },
  {
    id: 5,
    name: "Colombian Banana",
    category: "Bananas",
    price: "9.80",
    stars: 4,
    desc: "Sweet aroma",
    shadow: "yellow",
    image: require("../assets/images/banana.png"),
    color: (opacity: number) => `rgba(252, 223, 116, ${opacity})`,
  },
  {
    id: 6,
    name: "Brazilian Banana",
    category: "Bananas",
    price: "15.50",
    stars: 2,
    desc: "Full-bodied",
    shadow: "yellow",
    image: require("../assets/images/banana3.png"),
    color: (opacity: number) => `rgba(252, 223, 116, ${opacity})`,
  },
  {
    id: 7,
    name: "Ecuadorian Banana",
    category: "Bananas",
    price: "1.30",
    stars: 4,
    desc: "Creamy texture",
    shadow: "green",
    image: require("../assets/images/banana2.png"),
    color: (opacity: number) => `rgba(251, 246, 146, ${opacity})`,
  },
  {
    id: 8,
    name: "Hawaiian Pineapple",
    category: "Pineapple",
    price: "10.50",
    stars: 4,
    desc: "Tropical tang",
    shadow: "yellow",
    image: require("../assets/images/pineapple.png"),
    color: (opacity: number) => `rgba(252, 223, 116, ${opacity})`,
  },
  {
    id: 9,
    name: "Thai Pineapple",
    category: "Pineapple",
    price: "11.00",
    stars: 4,
    desc: "Exotic sweet",
    shadow: "yellow",
    image: require("../assets/images/pineapple2.png"),
    color: (opacity: number) => `rgba(252, 223, 116, ${opacity})`,
  },
  {
    id: 11,
    name: "Philippine Pineapple",
    category: "Pineapple",
    price: "12.30",
    stars: 4,
    desc: "Juicy delight",
    shadow: "yellow",
    image: require("../assets/images/pineapple.png"),
    color: (opacity: number) => `rgba(252, 223, 116, ${opacity})`,
  },
  {
    id: 12,
    name: "French Apple",
    category: "Apple",
    price: "12.30",
    stars: 4,
    desc: "Crisp taste",
    shadow: "green",
    image: require("../assets/images/apple.png"),
    color: (opacity: number) => `rgba(185, 250, 152, ${opacity})`,
  },
  {
    id: 13,
    name: "Canadian Apple",
    category: "Apple",
    price: "15.20",
    stars: 4,
    desc: "Juicy delight",
    shadow: "red",
    image: require("../assets/images/apple2.png"),
    color: (opacity: number) => `rgba(255, 130, 130, ${opacity})`,
  },
  {
    id: 14,
    name: "German Apple",
    category: "Apple",
    price: "9.00",
    stars: 4,
    desc: "Juicy delight",
    shadow: "green",
    image: require("../assets/images/apple3.png"),
    color: (opacity: number) => `rgba(185, 250, 152, ${opacity})`,
  },
  {
    id: 15,
    name: "Turkish Cherry",
    category: "Cherry",
    price: "12.00",
    stars: 4,
    desc: "Juicy delight",
    shadow: "red",
    image: require("../assets/images/cherry.png"),
    color: (opacity: number) => `rgba(250, 122, 122, ${opacity})`,
  },
  {
    id: 16,
    name: "Greek Cherry",
    category: "Cherry",
    price: "19.10",
    stars: 4,
    desc: "Juicy delight",
    shadow: "red",
    image: require("../assets/images/cherry2.png"),
    color: (opacity: number) => `rgba(250, 122, 122, ${opacity})`,
  },
  {
    id: 17,
    name: "Italian Cherry",
    category: "Cherry",
    price: "9.00",
    stars: 4,
    desc: "Juicy delight",
    shadow: "red",
    image: require("../assets/images/cherry3.png"),
    color: (opacity: number) => `rgba(250, 122, 122, ${opacity})`,
  },
];
